[project]
name = "mcpsample"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp>=1.24.0",
    "fastmcp",
    "pymupdf",
    "pillow",
    "pytesseract>=0.3.13",
    "easyocr>=1.7.2",
    "paramiko>=3.0.0",
    "chromadb>=0.4.0",
    "sentence-transformers>=2.0.0",
    "scp>=0.14.0",
    "httpx>=0.28.1",
]
